name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Updated Lint Baseline File
        uses: actions/upload-artifact@v4
        with:
          name: lint-baseline
          path: app/lint-baseline.xml

      - name: Build the app
        run: ./gradlew build
